const MOBILE_N_TABLET_BREAKPOINT = 480;
const TABLET_N_DESKTOP_BREAKPOINT = 768;
const DESKTOP_N_BIG_DESKTOP_BREAKPOINT = 1254;

const TABLET_N_DESKTOP_MEDIA_QUERY = `screen and (min-width: ${MOBILE_N_TABLET_BREAKPOINT}px) and (max-width: ${DESKTOP_N_BIG_DESKTOP_BREAKPOINT}px)`;
const DESKTOP_MEDIA_QUERY = `screen and (min-width: ${TABLET_N_DESKTOP_BREAKPOINT}px) and (max-width: ${DESKTOP_N_BIG_DESKTOP_BREAKPOINT}px)`;

const LESS_MOBILE_MEDIA_QUERY = `screen and (max-width: ${MOBILE_N_TABLET_BREAKPOINT}px)`;
const LESS_TABLET_MEDIA_QUERY = `screen and (max-width: ${TABLET_N_DESKTOP_BREAKPOINT}px)`;
const LESS_DESKTOP_MEDIA_QUERY = `screen and (max-width: ${DESKTOP_N_BIG_DESKTOP_BREAKPOINT}px)`;

const MORE_TABLET_MEDIA_QUERY = `screen and (min-width: ${MOBILE_N_TABLET_BREAKPOINT}px)`;
const MORE_DESKTOP_MEDIA_QUERY = `screen and (min-width: ${TABLET_N_DESKTOP_BREAKPOINT}px)`;
const MORE_BIG_DESKTOP_MEDIA_QUERY = `screen and (min-width: ${DESKTOP_N_BIG_DESKTOP_BREAKPOINT}px)`;

export {
  TABLET_N_DESKTOP_MEDIA_QUERY,
  DESKTOP_MEDIA_QUERY,
  LESS_MOBILE_MEDIA_QUERY,
  LESS_TABLET_MEDIA_QUERY,
  LESS_DESKTOP_MEDIA_QUERY,
  MORE_TABLET_MEDIA_QUERY,
  MORE_DESKTOP_MEDIA_QUERY,
  MORE_BIG_DESKTOP_MEDIA_QUERY,
};
